### ISSUE TITLE
Multiple instances in one scene don't work

### ISSUE THREAD

**Issue by tom-leys** [SIsilicon/Godot-3D-text-plugin#1]
Hi! Nice Plugin. I wanted to use it for my space game.

https://twitter.com/RecallSingular1

Steps to reproduce:
1. Open test scene "3D Text.tscn" which says "Hello! this is my 3D text plugin."
2. Duplicate the Label3D node
3a. Edit the text in the original node
3b. Edit the text in the duplicate node

Expected:
The two text fields should change by themselves, without affecting each other.

Result: 
It's clear they are both rendering into the same backing buffer and the text is only changed when you edit the original node. However, the dimensions of the second are independant of the first's dimensions.

**Comment by SIsilicon** [comment]
Thank you for reporting the bug! :)
It should be fixed now in the latest commit.
https://github.com/SIsilicon/Godot-3D-text-plugin/archive/7295511.zip

**Comment by tom-leys** [comment]
Wow, that was quick! Thanks. 

I will test this new version soon and let you know.

**Comment by tom-leys** [comment]
![image](https://user-images.githubusercontent.com/5285589/67435041-d2b99780-f647-11e9-91ca-400dbe42475d.png)

Confirmed fixed! Thanks very much :)
