### ISSUE TITLE
Add support for billboard text

### ISSUE THREAD

**Issue by AaronRecord** [SIsilicon/Godot-3D-text-plugin#17]
It'd be really nice to see support for billboard text (make the text always face the camera), as that's what I need for my project I'm working on.

**Comment by SIsilicon** [comment]
Excellent suggestion! Ill definitely implement it sometime.

**Comment by SIsilicon** [comment]
Implemented as of https://github.com/SIsilicon/Godot-3D-text-plugin/commit/0a7d9d47f0a1f3fd915c35352bdcd9b87e4156d4.
