### ISSUE TITLE
3D Text is not added to list of possible nodes by following Asset install in Godot

### ISSUE THREAD

**Issue by tom-leys** [SIsilicon/Godot-3D-text-plugin#2]
Steps:
1. Install 3D text using Godot Asset Store
2. Open a new scene - Add a 3D spatial node.
3. Press Ctrl-A to bring up the "add node" dialog
4. Type "3D"

Expected :
3D Text should be listed in the filtered nodes

Result: 
I cannot find 3D Text in the list. I cannot find it in the non-filtered list either.

**Comment by SIsilicon** [comment]
Actually, if you view the README file, the node's name is `Label3D`.

**Comment by Domigome** [comment]
I'm having the same issue:

![image](https://user-images.githubusercontent.com/75355506/146802331-90592a2d-4834-4354-848e-91b00e982818.png)

With Godot 3.4.stable and adding from inside the editor.
