### ISSUE TITLE
[Intermittent] 3d Text appears to hang the editor when game running

### ISSUE THREAD

**Issue by tom-leys** [SIsilicon/Godot-3D-text-plugin#4]
I can't reproduce it now. Hmmmm - perhaps it only occurs occasionally?
...

I'm using the head of the godot 3.1 branch in the GitHub repository - manually compiled. I'm not sure if you can repro this one but I'm going to mention it anyway...

What I did
1. Create a scene with a 3D label in it - in my case a sub-scene of a main scene
2. Launch the game
3. Observe game is running, editor is responsive
4. Do various things in the editor while game is running (in my case I just click on 2 scenetree nodes)

Observe:
Editor becomes unresponsive, it essentially has crashed / halted.

...

**Comment by SIsilicon** [comment]
Hmm ok. I'll try it out later. If it happens again for you, could you give me a log of some kind?

**Comment by tom-leys** [comment]
I am seeing similar hangs at other times without 3D text being involved. I don't know the reason but I no longer think it is your plugin.

Thanks
