### ISSUE TITLE
Example picture of 3dLabel in Use

### ISSUE THREAD

**Issue by tom-leys** [SIsilicon/Godot-3D-text-plugin#5]
Hi. 

Thanks for making this label, here's an example of it in use in my game. 

![image](https://user-images.githubusercontent.com/5285589/67436936-23cb8a80-f64c-11e9-9314-832b5277eb4e.png)

Feel free to reuse it if you like - I thought you might get a kick out of it.

That's all :)

**Comment by SIsilicon** [comment]
Oh it's very cool to see my work being used in practice. :)
