### ISSUE TITLE
Same settings but not 3d text

### ISSUE THREAD

**Issue by heilingbrunner** [SIsilicon/Godot-3D-text-plugin#6]
Hello,

i try to use 3d text plugin, but i do not get the same nice result. I am using Godot 3.1.2. Your sample project works correct, but my project shows a nice block, but not the text.

![3d text tscn](https://user-images.githubusercontent.com/1827209/70378205-0d3c7280-191e-11ea-88fd-cd4fa1251518.png)

There must be some other settings, which i can not find.

Thanks.

**Comment by SIsilicon** [comment]
![image](https://user-images.githubusercontent.com/34734122/70380546-f50f2800-190a-11ea-87bb-897d9b0e6239.png)

I don't seem to be having the same problem you are. Could you send a minimal reproduction project so that I may see what's up?

**Comment by heilingbrunner** [comment]
Yes. Thank you for the quick response.

[test3d.zip](https://github.com/SIsilicon/Godot-3D-text-plugin/files/3935704/test3d.zip)

**Comment by SIsilicon** [comment]
Ok. [It should be fixed now](https://github.com/SIsilicon/Godot-3D-text-plugin/archive/master.zip).
Let me know if it works.

**Comment by heilingbrunner** [comment]
Looks good. :-)

Thank you.

![3d text tscn-2](https://user-images.githubusercontent.com/1827209/70393150-83f17280-19e7-11ea-88c5-78dba9272178.png)
